### ISSUE TITLE
Support for Kubernetes 1.28.x

### ISSUE THREAD

**Issue by mreichardt95** [YAKEcloud/yake#1349]
Currently, the Helm Chart `configuration/configuration/Chart.yaml` limits Kubernetes max version to 1.27.x
I've deployed YAKE to a cluster with 1.28.6 without any issue.

Would it be possible to bump this limit to support v1.28.x?

**Comment by j2L4e** [comment]
> I've deployed YAKE to a cluster with 1.28.6 without any issue.
That's great to hear!

We'll update our CI to include 1.28 and add support with the next release.

**Comment by j2L4e** [comment]
We've added support for 1.28 with [1.89.0-2](https://github.com/YAKEcloud/yake/releases/tag/v1.89.0-2).

**Comment by mreichardt95** [comment]
Thank you very much, but I don't see 0b5e2e0 being included in https://github.com/YAKEcloud/yake/commits/v1.89.0-2/

**Comment by j2L4e** [comment]
Yep, you're correct. I backported it to the 1.89 branch. https://github.com/YAKEcloud/yake/releases/tag/v1.89.0-3
