### ISSUE TITLE
etcd backup via Swift does not allow to use applicationSecret

### ISSUE THREAD

**Issue by Lappihuan** [YAKEcloud/yake#1380]
The storageProvicer "Swift" for the etcd backup does not allow to configure a applicationSecret, only username and password:
https://github.com/YAKEcloud/yake/blob/019dfd3452bc7c76a1216f1bc05632861429b19a/helmcharts/etcd/templates/secret-etcd-backup.yaml#L28-L33

https://github.com/YAKEcloud/yake/blob/019dfd3452bc7c76a1216f1bc05632861429b19a/configuration/configuration/templates/etcd.yaml#L35-L41

But etcd-backup-restore would support it: https://github.com/gardener/etcd-backup-restore/blob/a73fb83f171edf3bddfae43f11b6c163474d1f34/example/storage-provider-secrets/02-openstack-swift-storage-secret.yaml#L50-L52

**Comment by j2L4e** [comment]
https://github.com/gardener-community/etcd/pull/15

**Comment by j2L4e** [comment]
closed via #1398
